# modules/node-identity.nix
# Defines the kindling.nodeIdentity option interface.
# Profiles read from these options to parameterize machine-specific values.
# Values are set from node.json (generated by kindling CLI from node.yaml).
{
  config,
  lib,
  ...
}: let
  inherit (lib) mkOption types;
  cfg = config.kindling.nodeIdentity;
in {
  options.kindling.nodeIdentity = {
    # Allow extra fields from node.json without errors
    _module.freeformType = types.attrsOf types.anything;

    # ── Core identity ──────────────────────────────────────────
    version = mkOption {
      type = types.str;
      default = "1";
      description = "Node identity schema version";
    };

    profile = mkOption {
      type = types.str;
      description = "Machine profile name from kindling-profiles";
      example = "macos-developer";
    };

    hostname = mkOption {
      type = types.str;
      description = "Machine hostname";
      example = "cid";
    };

    # ── User ───────────────────────────────────────────────────
    user = {
      name = mkOption {
        type = types.str;
        description = "Primary user account name";
        example = "drzzln";
      };

      uid = mkOption {
        type = types.int;
        description = "User ID";
        example = 1003;
      };

      shell = mkOption {
        type = types.str;
        default = "blzsh";
        description = "Login shell (blzsh, zsh, bash)";
      };

      email = mkOption {
        type = types.str;
        default = "";
        description = "User email address";
      };
    };

    # ── Secrets ────────────────────────────────────────────────
    secrets = {
      provider = mkOption {
        type = types.str;
        default = "sops";
        description = "Secrets provider (sops, vault, 1password)";
      };

      age_key_file = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Path to age key file for SOPS decryption";
        example = "~/.config/sops/age/keys.txt";
      };

      ssh_authorized_keys = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "SSH public keys to deploy to authorized_keys";
      };

      tls_certificates = mkOption {
        type = types.listOf (types.submodule {
          options = {
            domain = mkOption {type = types.str;};
            cert_file = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            key_file = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            issuer = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
          };
        });
        default = [];
        description = "TLS certificates managed on this node";
      };

      age_keys = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Additional age public keys for encryption";
      };
    };

    # ── Hardware ──────────────────────────────────────────────
    hardware = {
      platform = mkOption {
        type = types.str;
        default = "aarch64-darwin";
        description = "Nix system platform string";
        example = "x86_64-linux";
      };

      cpu = {
        vendor = mkOption {
          type = types.str;
          default = "";
          description = "CPU vendor for microcode (intel, amd, or empty)";
        };

        cores = mkOption {
          type = types.nullOr types.int;
          default = null;
          description = "Number of physical CPU cores";
        };

        threads = mkOption {
          type = types.nullOr types.int;
          default = null;
          description = "Number of logical CPU threads";
        };

        model = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "CPU model name";
        };
      };

      memory = mkOption {
        type = types.nullOr (types.submodule {
          options = {
            size_gb = mkOption {
              type = types.float;
              description = "Total memory in GB";
            };
          };
        });
        default = null;
        description = "Memory configuration";
      };

      disks = mkOption {
        type = types.listOf (types.submodule {
          options = {
            device = mkOption {type = types.str;};
            size = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            disk_type = mkOption {
              type = types.nullOr types.str;
              default = null;
              description = "Disk type (ssd, nvme, hdd)";
            };
            mount_point = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
          };
        });
        default = [];
        description = "Disk devices";
      };

      gpus = mkOption {
        type = types.listOf (types.submodule {
          options = {
            vendor = mkOption {type = types.str;};
            model = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            vram_mb = mkOption {
              type = types.nullOr types.int;
              default = null;
            };
          };
        });
        default = [];
        description = "GPU devices";
      };

      network_interfaces = mkOption {
        type = types.listOf (types.submodule {
          options = {
            name = mkOption {type = types.str;};
            mac = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            speed_mbps = mkOption {
              type = types.nullOr types.int;
              default = null;
            };
          };
        });
        default = [];
        description = "Hardware network interfaces";
      };

      kernel = {
        modules = mkOption {
          type = types.listOf types.str;
          default = [];
          description = "Kernel modules to load";
        };

        params = mkOption {
          type = types.listOf types.str;
          default = [];
          description = "Kernel boot parameters";
        };
      };

      filesystems = mkOption {
        type = types.nullOr types.attrs;
        default = {};
        description = "Filesystem mount configuration";
      };
    };

    # ── Network ────────────────────────────────────────────────
    network = {
      ssh = mkOption {
        type = types.attrs;
        default = {};
        description = "SSH client configuration (builder, tunnel, hosts)";
      };

      interfaces = mkOption {
        type = types.attrsOf (types.submodule {
          options = {
            address = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            prefix_length = mkOption {
              type = types.nullOr types.int;
              default = null;
            };
            gateway = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            mac = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            mtu = mkOption {
              type = types.nullOr types.int;
              default = null;
            };
          };
        });
        default = {};
        description = "Network interface configurations";
      };

      hosts = mkOption {
        type = types.attrsOf types.str;
        default = {};
        description = "Extra /etc/hosts entries (hostname -> IP)";
      };

      firewall = {
        allowed_tcp_ports = mkOption {
          type = types.listOf types.int;
          default = [];
          description = "TCP ports to allow through firewall";
        };

        allowed_udp_ports = mkOption {
          type = types.listOf types.int;
          default = [];
          description = "UDP ports to allow through firewall";
        };

        rules = mkOption {
          type = types.listOf types.str;
          default = [];
          description = "Additional firewall rules";
        };
      };

      dns_servers = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "DNS server addresses";
      };

      ntp_servers = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "NTP server addresses";
      };

      vpn = mkOption {
        type = types.listOf (types.submodule {
          options = {
            public_key = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            endpoint = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            allowed_ips = mkOption {
              type = types.listOf types.str;
              default = [];
            };
          };
        });
        default = [];
        description = "VPN peer configurations (WireGuard) — legacy, prefer vpn_links";
      };

      vpn_links = mkOption {
        type = types.listOf (types.submodule {
          options = {
            name = mkOption {
              type = types.str;
              description = "WireGuard interface name (e.g., wg-k8s)";
            };
            private_key_file = mkOption {
              type = types.nullOr types.str;
              default = null;
              description = "Path to WireGuard private key file";
            };
            listen_port = mkOption {
              type = types.nullOr types.int;
              default = null;
              description = "UDP listen port (null = client mode)";
            };
            address = mkOption {
              type = types.nullOr types.str;
              default = null;
              description = "Interface address with prefix (e.g., 10.100.0.1/24)";
            };
            profile = mkOption {
              type = types.nullOr types.str;
              default = null;
              description = "Link profile (k8s-control-plane, k8s-full, site-to-site, mesh)";
            };
            persistent_keepalive = mkOption {
              type = types.nullOr types.int;
              default = null;
              description = "Default keepalive for all peers (seconds)";
            };
            mtu = mkOption {
              type = types.nullOr types.int;
              default = null;
              description = "Interface MTU";
            };
            dns = mkOption {
              type = types.listOf types.str;
              default = [];
              description = "DNS servers for this link";
            };
            peers = mkOption {
              type = types.listOf (types.submodule {
                options = {
                  public_key = mkOption {
                    type = types.nullOr types.str;
                    default = null;
                  };
                  endpoint = mkOption {
                    type = types.nullOr types.str;
                    default = null;
                  };
                  allowed_ips = mkOption {
                    type = types.listOf types.str;
                    default = [];
                  };
                  persistent_keepalive = mkOption {
                    type = types.nullOr types.int;
                    default = null;
                  };
                  preshared_key_file = mkOption {
                    type = types.nullOr types.str;
                    default = null;
                  };
                };
              });
              default = [];
              description = "WireGuard peers";
            };
            firewall = mkOption {
              type = types.submodule {
                options = {
                  trust_interface = mkOption {
                    type = types.bool;
                    default = false;
                  };
                  allowed_tcp_ports = mkOption {
                    type = types.listOf types.int;
                    default = [];
                  };
                  allowed_udp_ports = mkOption {
                    type = types.listOf types.int;
                    default = [];
                  };
                  incoming_udp_port = mkOption {
                    type = types.nullOr types.int;
                    default = null;
                  };
                };
              };
              default = {};
              description = "Per-link firewall configuration";
            };
          };
        });
        default = [];
        description = "WireGuard VPN link configurations for blackmatter-vpn";
      };
    };

    # ── Nix configuration ─────────────────────────────────────
    nix = {
      trusted_users = mkOption {
        type = types.listOf types.str;
        default = ["root"];
        description = "Users trusted by the Nix daemon";
      };

      attic = {
        token_file = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Path to Attic cache auth token";
        };

        netrc_file = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Path to netrc file for substituter authentication";
        };

        url = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Attic cache URL";
        };

        public_keys = mkOption {
          type = types.listOf types.str;
          default = [];
          description = "Attic cache public signing keys";
        };

        cache_name = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Attic cache name";
        };
      };
    };

    # ── Kubernetes ─────────────────────────────────────────────
    kubernetes = {
      role = mkOption {
        type = types.nullOr (types.enum ["server" "agent"]);
        default = null;
        description = "K3s role (server or agent)";
      };

      server_addr = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "K3s server address (for agents joining a cluster)";
      };

      cluster_cidr = mkOption {
        type = types.nullOr types.str;
        default = "10.42.0.0/16";
        description = "Pod network CIDR";
      };

      service_cidr = mkOption {
        type = types.nullOr types.str;
        default = "10.43.0.0/16";
        description = "Service network CIDR";
      };

      node_labels = mkOption {
        type = types.attrsOf types.str;
        default = {};
        description = "Kubernetes node labels";
      };

      node_taints = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Kubernetes node taints";
      };

      clusters = mkOption {
        type = types.listOf (types.submodule {
          options = {
            name = mkOption {type = types.str;};
            server = mkOption {type = types.str;};
          };
        });
        default = [];
        description = "Known cluster endpoints for kubectl config";
      };
    };

    # ── FluxCD ─────────────────────────────────────────────────
    fluxcd = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable FluxCD GitOps";
      };

      source = mkOption {
        type = types.str;
        default = "";
        description = "FluxCD source repository URL";
      };

      reconcile = mkOption {
        type = types.attrs;
        default = {};
        description = "FluxCD reconciliation settings";
      };
    };

    # ── Services ───────────────────────────────────────────────
    services = {
      custom = mkOption {
        type = types.listOf (types.submodule {
          options = {
            name = mkOption {type = types.str;};
            port = mkOption {
              type = types.nullOr types.int;
              default = null;
            };
            health_endpoint = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            protocol = mkOption {
              type = types.str;
              default = "http";
            };
          };
        });
        default = [];
        description = "Custom services running on this node";
      };
    };

    # ── Workspace ──────────────────────────────────────────────
    workspace = {
      orgs = mkOption {
        type = types.listOf (types.submodule {
          options = {
            name = mkOption {type = types.str;};
            base_dir = mkOption {type = types.str;};
            github_token_file = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
          };
        });
        default = [];
        description = "Workspace organizations for tend";
      };

      zoekt_repos = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Repository paths to index with Zoekt";
      };

      codesearch = mkOption {
        type = types.nullOr types.attrs;
        default = {};
        description = "Codesearch daemon configuration";
      };
    };

    # ── Git ─────────────────────────────────────────────────────
    git = {
      user = {
        name = mkOption {
          type = types.str;
          default = "";
          description = "Git author name";
        };

        email = mkOption {
          type = types.str;
          default = "";
          description = "Git author email";
        };
      };
    };

    # ── macOS ───────────────────────────────────────────────────
    macos = {
      capslock_to_escape = mkOption {
        type = types.bool;
        default = true;
        description = "Remap Caps Lock to Escape (persists via LaunchAgent)";
      };

      homebrew = {
        casks = mkOption {
          type = types.listOf types.str;
          default = [];
          description = "Homebrew casks to install";
          example = [ "slack" "vlc" "zoom" ];
        };
      };

      determinate_nix = mkOption {
        type = types.bool;
        default = true;
        description = "Use Determinate Nix (disables nix-darwin nix management)";
      };

      chrome = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Configure Chrome settings";
        };

        extension_ids = mkOption {
          type = types.listOf types.str;
          default = [];
          description = "Chrome extension IDs to install";
          example = [ "aeblfdkhhhdcdjpifhhbdiojplfjncoa" ];
        };
      };

      containers = {
        podman = mkOption {
          type = types.bool;
          default = false;
          description = "Enable Podman container runtime";
        };
      };

      appstore = {
        apps = mkOption {
          type = types.attrsOf types.int;
          default = {};
          description = "App Store apps to install (name -> Apple ID)";
          example = { Xcode = 497799835; };
        };
      };

      tailscale = {
        enable = mkOption {
          type = types.bool;
          default = false;
          description = "Enable Tailscale VPN client";
        };
      };

      amimori = {
        enable = mkOption {
          type = types.bool;
          default = false;
          description = "Enable amimori network profiler daemon";
        };
      };
    };

    # ── Tools ───────────────────────────────────────────────────
    tools = {
      editor = mkOption {
        type = types.str;
        default = "blnvim";
        description = "Default editor";
      };

      claude = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Enable Claude Code integration";
        };
      };

      cursor = {
        enable = mkOption {
          type = types.bool;
          default = false;
          description = "Enable Cursor IDE configuration";
        };
      };

      mcp_services = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Enable MCP service daemons (zoekt, codesearch, tend)";
        };
      };

      window_manager = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Enable window management (AeroSpace)";
        };
      };

      stylix = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Enable Stylix color theme targets";
        };
      };
    };

    # ── Atlassian ───────────────────────────────────────────────
    atlassian = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable Atlassian CLI integration";
      };

      site = mkOption {
        type = types.str;
        default = "";
        description = "Atlassian site name (e.g. 'mycompany')";
      };

      site_url = mkOption {
        type = types.str;
        default = "";
        description = "Atlassian site URL";
      };

      email = mkOption {
        type = types.str;
        default = "";
        description = "Atlassian account email";
      };

      account_id = mkOption {
        type = types.str;
        default = "";
        description = "Atlassian account ID";
      };
    };

    # ── SSH Server ──────────────────────────────────────────────
    ssh_server = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable SSH server for fleet peer access";
      };

      authorized_keys = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "SSH public keys authorized for login";
      };
    };

    # ── Fleet ──────────────────────────────────────────────────
    fleet = {
      controller = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Fleet controller node name or URL";
      };

      environment = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Environment label (prod, staging, dev)";
      };

      owner = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Owner of this node";
      };

      team = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Team responsible for this node";
      };

      tags = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Tags for node categorization";
      };

      maintenance_windows = mkOption {
        type = types.listOf (types.submodule {
          options = {
            day = mkOption {
              type = types.nullOr types.str;
              default = null;
              description = "Day of week (monday, tuesday, etc.)";
            };
            start_hour = mkOption {
              type = types.nullOr types.int;
              default = null;
              description = "Start hour (0-23)";
            };
            duration_hours = mkOption {
              type = types.nullOr types.int;
              default = null;
              description = "Duration in hours";
            };
          };
        });
        default = [];
        description = "Scheduled maintenance windows";
      };

      dependencies = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Node names this node depends on";
      };

      peers = mkOption {
        type = types.listOf (types.submodule {
          options = {
            name = mkOption {type = types.str;};
            hostname = mkOption {type = types.str;};
            ssh_user = mkOption {
              type = types.str;
              default = "root";
            };
          };
        });
        default = [];
        description = "Fleet peer nodes for remote management";
      };
    };
  };
}
