# modules/node-identity.nix
# Defines the kindling.nodeIdentity option interface.
# Profiles read from these options to parameterize machine-specific values.
# Values are set from node.json (generated by kindling CLI from node.yaml).
{
  config,
  lib,
  ...
}: let
  inherit (lib) mkOption types;
  cfg = config.kindling.nodeIdentity;
in {
  options.kindling.nodeIdentity = {
    # ── Core identity ──────────────────────────────────────────
    profile = mkOption {
      type = types.str;
      description = "Machine profile name from kindling-profiles";
      example = "macos-developer";
    };

    hostname = mkOption {
      type = types.str;
      description = "Machine hostname";
      example = "cid";
    };

    # ── User ───────────────────────────────────────────────────
    user = {
      name = mkOption {
        type = types.str;
        description = "Primary user account name";
        example = "drzzln";
      };

      uid = mkOption {
        type = types.int;
        description = "User ID";
        example = 1003;
      };

      shell = mkOption {
        type = types.str;
        default = "zsh";
        description = "Login shell (zsh, bash, blzsh)";
      };

      email = mkOption {
        type = types.str;
        default = "";
        description = "User email address";
      };
    };

    # ── Secrets ────────────────────────────────────────────────
    secrets = {
      provider = mkOption {
        type = types.str;
        default = "sops";
        description = "Secrets provider (sops, vault, 1password)";
      };

      age_key_file = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Path to age key file for SOPS decryption";
        example = "~/.config/sops/age/keys.txt";
      };
    };

    # ── Nix configuration ─────────────────────────────────────
    nix = {
      trusted_users = mkOption {
        type = types.listOf types.str;
        default = ["root"];
        description = "Users trusted by the Nix daemon";
      };

      attic = {
        token_file = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Path to Attic cache auth token";
        };

        netrc_file = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Path to netrc file for substituter authentication";
        };
      };
    };

    # ── Network ────────────────────────────────────────────────
    network = {
      interfaces = mkOption {
        type = types.attrsOf (types.submodule {
          options = {
            address = mkOption {type = types.str;};
            prefixLength = mkOption {
              type = types.int;
              default = 24;
            };
            gateway = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
          };
        });
        default = {};
        description = "Network interface configurations";
      };

      ssh = mkOption {
        type = types.attrs;
        default = {};
        description = "SSH client configuration (builder, tunnel, hosts)";
      };

      hosts = mkOption {
        type = types.attrsOf types.str;
        default = {};
        description = "Extra /etc/hosts entries (hostname -> IP)";
      };

      firewall = {
        allowed_tcp_ports = mkOption {
          type = types.listOf types.int;
          default = [];
          description = "TCP ports to allow through firewall";
        };

        allowed_udp_ports = mkOption {
          type = types.listOf types.int;
          default = [];
          description = "UDP ports to allow through firewall";
        };
      };
    };

    # ── Hardware (NixOS only) ──────────────────────────────────
    hardware = {
      platform = mkOption {
        type = types.str;
        default = "aarch64-darwin";
        description = "Nix system platform string";
        example = "x86_64-linux";
      };

      cpu = mkOption {
        type = types.str;
        default = "";
        description = "CPU vendor for microcode (intel, amd, or empty)";
      };

      filesystems = mkOption {
        type = types.attrs;
        default = {};
        description = "Filesystem mount configuration";
      };

      kernel = {
        modules = mkOption {
          type = types.listOf types.str;
          default = [];
          description = "Kernel modules to load";
        };

        params = mkOption {
          type = types.listOf types.str;
          default = [];
          description = "Kernel boot parameters";
        };
      };
    };

    # ── Kubernetes ─────────────────────────────────────────────
    kubernetes = {
      role = mkOption {
        type = types.nullOr (types.enum ["server" "agent"]);
        default = null;
        description = "K3s role (server or agent)";
      };

      server_addr = mkOption {
        type = types.str;
        default = "";
        description = "K3s server address (for agents joining a cluster)";
      };

      cluster_cidr = mkOption {
        type = types.str;
        default = "10.42.0.0/16";
        description = "Pod network CIDR";
      };

      service_cidr = mkOption {
        type = types.str;
        default = "10.43.0.0/16";
        description = "Service network CIDR";
      };

      node_labels = mkOption {
        type = types.attrsOf types.str;
        default = {};
        description = "Kubernetes node labels";
      };

      node_taints = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Kubernetes node taints";
      };

      clusters = mkOption {
        type = types.listOf (types.submodule {
          options = {
            name = mkOption {type = types.str;};
            server = mkOption {type = types.str;};
          };
        });
        default = [];
        description = "Known cluster endpoints for kubectl config";
      };
    };

    # ── FluxCD ─────────────────────────────────────────────────
    fluxcd = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable FluxCD GitOps";
      };

      source = mkOption {
        type = types.str;
        default = "";
        description = "FluxCD source repository URL";
      };

      reconcile = mkOption {
        type = types.attrs;
        default = {};
        description = "FluxCD reconciliation settings";
      };
    };

    # ── Workspace ──────────────────────────────────────────────
    workspace = {
      orgs = mkOption {
        type = types.listOf (types.submodule {
          options = {
            name = mkOption {type = types.str;};
            base_dir = mkOption {type = types.str;};
            github_token_file = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
          };
        });
        default = [];
        description = "Workspace organizations for tend";
      };

      zoekt_repos = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Repository paths to index with Zoekt";
      };

      codesearch = mkOption {
        type = types.attrs;
        default = {};
        description = "Codesearch daemon configuration";
      };
    };

    # ── Git ─────────────────────────────────────────────────────
    git = {
      user = {
        name = mkOption {
          type = types.str;
          default = "";
          description = "Git author name";
        };

        email = mkOption {
          type = types.str;
          default = "";
          description = "Git author email";
        };
      };
    };

    # ── Fleet ──────────────────────────────────────────────────
    fleet = {
      controller = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Fleet controller node name";
      };

      peers = mkOption {
        type = types.listOf (types.submodule {
          options = {
            name = mkOption {type = types.str;};
            hostname = mkOption {type = types.str;};
            ssh_user = mkOption {
              type = types.str;
              default = "root";
            };
          };
        });
        default = [];
        description = "Fleet peer nodes for remote management";
      };
    };
  };
}
