# profiles/k3s-cloud-server-ssm/default.nix
#
# Single-node K3s server profile for the SSM-runtime pattern. The AMI
# is generic — every per-cluster runtime value (api hostname, CAs,
# Cilium values, …) flows from SSM at first-boot via tatara-script.
# Predictable kubeconfig: same CA material across infinite cluster
# rebuilds because k3s respects pre-existing CAs in
# /var/lib/rancher/k3s/server/tls/.
#
# Sister to profiles/portao — same first-boot orchestration shape, K3s
# instead of WireGuard.
#
# What this profile does NOT include (and why):
#   - blackmatter.k3s wrapper        — uses NixOS stock services.k3s; the
#                                       wrapper assumes kindling.nodeIdentity.
#   - kindling-init / cluster-config.json — superseded by SSM-runtime.
#   - VPN / WireGuard                — operator access via SG :6443 from
#                                       operator_cidrs; portao path comes later.
#   - FluxCD                          — GitOps comes after the cluster is
#                                       validated.
#   - FedRAMP compliance baseline     — orthogonal; layer in via additional
#                                       imports if/when needed.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  k3sBootstrapScript = ./k3s-bootstrap.tlisp;
in {
  imports = [
    "${modulesPath}/virtualisation/amazon-image.nix"
  ];

  # ── Hostname + locale ──────────────────────────────────────────────
  networking.hostName = "k3s-cloud-server";
  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";
  system.stateVersion = "25.11";

  # ── Networking ──────────────────────────────────────────────────────
  # K3s API + node-to-node + Cilium (vxlan tunnel + health checks).
  # SG enforces the operator-IP allowlist on :22 + :6443; the firewall
  # here is in-instance defense-in-depth.
  networking.firewall.allowedTCPPorts = [
    22       # SSH
    6443     # K3s API
    10250    # kubelet (cluster-internal but K3s opens for metrics-server)
    10257    # kube-controller-manager
    10259    # kube-scheduler
  ];
  networking.firewall.allowedUDPPorts = [
    8472     # Cilium vxlan tunnel
  ];

  # ── SSH ────────────────────────────────────────────────────────────
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
    };
  };

  # ── K3s service (gated on first-boot completion) ───────────────────
  # NixOS stock services.k3s with --config flag pointing at the file
  # k3s-bootstrap.service writes. K3s service waits for the bootstrap
  # sentinel to exist via ConditionPathExists; without it, K3s never
  # starts.
  services.k3s = {
    enable = true;
    role = "server";
    extraFlags = [
      "--config=/etc/rancher/k3s/config.yaml"
    ];
  };

  # The K3s systemd unit is generated by NixOS; we extend it here to
  # gate startup on bootstrap completion + add the dependency edge.
  systemd.services.k3s = {
    after = [ "network-online.target" "k3s-bootstrap.service" ];
    requires = [ "k3s-bootstrap.service" ];
    unitConfig.ConditionPathExists = "/var/lib/k3s-bootstrap-complete";
  };

  # ── First-boot bootstrap (tatara-script) ───────────────────────────
  # Sister to portao-init.service. Reads instance tag pleme:k3s:ssm-prefix
  # → ssm get-parameters-by-path → writes CAs + config.yaml + Cilium
  # manifest + Route53 A record.
  systemd.services.k3s-bootstrap = {
    description = "K3s bootstrap: SSM → CA files + config.yaml + Cilium manifest + Route53 A record";
    wantedBy = [ "multi-user.target" ];
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    # Pinned PATH — every binary the .tlisp `exec-capture`s must be
    # listed here so it fails at build time if missing (mirrors the
    # portao discipline).
    path = with pkgs; [
      tatara-script
      awscli2
      curl
      coreutils
      bash
    ];
    unitConfig = {
      # Idempotency: skip if already complete.
      ConditionPathExists = "!/var/lib/k3s-bootstrap-complete";
    };
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.tatara-script}/bin/tatara-script ${k3sBootstrapScript}";
    };
  };

  # ── Required runtime tooling ───────────────────────────────────────
  environment.systemPackages = with pkgs; [
    k3s          # kubectl etc. + the binary services.k3s manages
    awscli2      # for k3s-bootstrap + operator break-glass
    curl
    htop
    lsof
  ];

  # ── Boot + system tuning ──────────────────────────────────────────
  boot.kernelParams = [
    "transparent_hugepage=never"
  ];
  boot.loader.timeout = lib.mkDefault 3;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";

  services.journald.extraConfig = ''
    Storage=volatile
    SystemMaxUse=200M
  '';

  systemd.network.wait-online.enable = false;

  # ── Nix ─────────────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # ── Hardware tuning (NVMe) ─────────────────────────────────────────
  services.smartd.enable = false;
  services.fstrim.enable = true;
  services.udev.extraRules = ''
    ACTION=="add|change", KERNEL=="nvme[0-9]n1", ATTR{queue/scheduler}="none"
    ACTION=="add|change", KERNEL=="nvme[0-9]n1", ATTR{queue/nr_requests}="1024"
  '';
}
